export { default as Splash } from './Splash'
export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Create } from './Create'
export { default as Games } from './Games'
export { default as Profile } from './Profile'
export { default as Community } from './Community'
export { default as MindGarden } from './MindGarden'
export { default as Assessment } from './Assessment'
export { default as ArtCreator } from './ArtCreator'
export { default as MusicCreator } from './MusicCreator'
export { default as StoryCreator } from './StoryCreator'
export { default as PoemCreator } from './PoemCreator'
export { default as MyWorks } from './MyWorks'
export { default as Favorites } from './Favorites'
export { default as StoryLibrary } from './StoryLibrary'
export { default as FruitMatch } from './FruitMatch'
export { default as TankBattle } from './TankBattle'
export { default as ChessGame } from './ChessGame'
export { default as ChineseChess } from './ChineseChess'
export { default as CrystalMatch } from './CrystalMatch'
export { default as AIEncyclopedia } from './AIEncyclopedia'
export { default as PictureBook } from './PictureBook'
export { default as FourClassics } from './FourClassics'
export { default as ChineseClassics } from './ChineseClassics'
export { default as WhackAMole } from './WhackAMole'
export { default as NumberPuzzle } from './NumberPuzzle'
export { default as JigsawPuzzle } from './JigsawPuzzle'
export { default as Search } from './Search'
export { default as ChildrenSongs } from './ChildrenSongs'
export { default as EnglishBook } from './EnglishBook'
export { default as WhyQuestions } from './WhyQuestions'

// 温暖小屋组件
export { default as WarmHouse } from './WarmHouse'
export { default as AICompanion } from './AICompanion'
export { default as MoodDiary } from './MoodDiary'
export { default as WarmRadio } from './WarmRadio'
export { default as WishTree } from './WishTree'

// 家长端组件
export { default as ParentLogin } from './ParentLogin'
export { default as ParentLayout } from './ParentLayout'
export { default as ParentDashboard } from './ParentDashboard'
export { default as ChildrenManagement } from './ChildrenManagement'
export { default as LearningData } from './LearningData'
export { default as UsageControl } from './UsageControl'
export { default as GrowthReport } from './GrowthReport'
export { default as ParentSettings } from './ParentSettings'

// AI作业助手组件
export { default as HomeworkHelper } from './HomeworkHelper'
export { default as HomeworkAnswer } from './HomeworkAnswer'
export { default as HomeworkHistory } from './HomeworkHistory'
